name: Release templates
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure GIT
        run: |
          git config --global user.name "Gluon Bot"
          git config --global user.email "githubbot@gluonhq.com"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Upload templates to Nexus
        run: ./gradlew clean uploadPublished

      - name: Create templates
        run: ./gradlew packageTemplates

      - name: Upload templates
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/templates"
          target: "ideplugins/templates"

      - name: Commit next development version
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          newVersion=${TAG%.*}.$((${TAG##*.} + 1)) # Update version by 1
          sed -i "s/^version = '.*'$/version = '$newVersion-SNAPSHOT'/g" build.gradle
          git commit build.gradle -m "New ide templates development version: $newVersion"
          git push https://gluon-bot:$GITHUB_PASSWORD@github.com/$GITHUB_REPOSITORY HEAD:master
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}